HomeHealthCareMVC/Models/User.cs
using System;

public class User
{
   
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public Nullable<System.DateTime> DOB { get; set; }
    public string TypeOfUser { get; set; }

}

HomeHealthCareMVC/Models/UserLogin.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HomeHealthCareMVC.Models
{
    public class UserLogin
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }

        //  [Required]
        //  [StringLength(maximumLength: 40, MinimumLength = 5,
        //ErrorMessage = "Username {0} should have {1} maximum characters and {2} minimum characters")]
        //  public string Username { get; set; }
        //  [Required]
        //  [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        //  [DataType(DataType.Password)]
        //  [Display(Name = "Password")]
        //  public string Password { get; set; }

        //  [DataType(DataType.Password)]
        //  [Display(Name = "Confirm password")]
        //  [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        //  public string ConfirmPassword { get; set; }
        //  public UserType UserType { get; set; }
    }
}

HomeHealthCareMVC/Models/UserType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HomeHealthCareMVC.Models
{
    public enum UserType
    {
        Doctor,
        Patient,
        Admin
    }
}

HomeHealthCareMVC/Models/Users.cs
//using System;
//using System.ComponentModel.DataAnnotations;

//namespace HomeHealthCareMVC.Models
//{
//    public class Users
//    {
     

//        public int ID { get; set; }
     
//        [StringLength(maximumLength: 40, MinimumLength = -1,
//         ErrorMessage = "Username {0} should have {1} maximum characters and {2} minimum characters")]
//        [Required(
//            ErrorMessage = "Username Required")]
//        public string Username { get; set; }
//        [Required (
//             ErrorMessage = "Password Required")]
//        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
//        [DataType(DataType.Password)]
//        [Display(Name = "Password")]
//        public string Password { get; set; }
//        [Required]
//        public string FirstName { get; set; }
//        [Required]
//        public string LastName { get; set; }
//        [Required]
//        public UserType UserType { get; set; }
//        public DateTime? CreatedDateTime { get; set; }
//    }
//}

HomeHealthCareMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeHealthCareMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HomeHealthCareMVC/Controllers/HomeHealthCareController.cs
using HomeHealthCareMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeHealthCareMVC.Controllers
{
    public class HomeHealthCareController : Controller
    {
        // GET: HomeHealthCare
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Register()
        {
           
            return View();
        }
        public ActionResult AdminRegister()
        {
            return View();
        }
        public ActionResult AdminLogin()
        {
            return View();
        }
        public ActionResult Admin()
        {
            return View();
        }
        public ActionResult Logout()
        {
            return View();
        }
    }
}

HomeHealthCareMVC/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HealthCare</title>
    <link rel="icon" type="image/png" href="~/Image/loginlogo.jpg" , 16px ,16px>
    <link rel="stylesheet" href="~/Content/healthcare.css">
    <script defer src="~/Scripts/Appointment.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

</head>
<body>
    <div>
        <ul class="btn btn-info btnlogin" style="margin-left:1100px">
            <li>@Html.ActionLink("LogOut", "Logout", "HomeHealthCare", new { area = "" }, null)</li>
        </ul>
    </div>

    <div>
        <aside id="leftmenu">
            <img src="~/Image/Welcomeimg.png" width="290" height="400" alt="welcomeimage" />

        </aside>
        <main id="main">
            <h3><span style="color: #FE1D42 ;"> Get</span>  HomeHealthCare</h3>
            <h3>Services <span style="color: #FE1D42 ;">at your</span></h3>
            <h3><span style="color: #FE1D42 ;">doorstep</span></h3>
            <h6>Nursing Care | Elder Care | Attender</h6>
            <h6>Covid Care | ICU setup at home</h6>
            <form id="myForm">
                <label for="txtdoctorname"><b>Doctor Name</b></label>
                <select class="form-control" id="txtdoctorname" name="doctorname"></select>
                <label for="txtspecialist"><b>Specialist</b></label>
                <select class="form-control" id="txtspecialist" name="specialist"></select>
                <label for="date">Date</label><br />
                <input type="date" name="date" id="txtdate" autocomplete="off" style="width:100%">
            </form>
            <h3><button id="appointment" class="btn btn-info btnlogin">Book Appointment</button></h3>
        </main>
    </div>

</body>
</html>

HomeHealthCareMVC/Views/HomeHealthCare/Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/Register.css" rel="stylesheet" />
    <script defer src="~/Scripts/Login.js"></script>
</head>
<body>
    <div class="container">
        <form id="signin" class="form">
            <h1>HomeHealthCare</h1>

            <div class="form-field">
                <label for="txtEmail">Email:</label>
                <input type="text" name="email" id="txtEmail" autocomplete="off">
                <small></small>
            </div>

            <div class="form-field">
                <label for="txtPassword">Password:</label>
                <input type="password" name="password" id="txtPassword" autocomplete="off">
                <small></small>
            </div>
            <p></p>
            <div class="form-field">
                <input type="submit" id="txtlogin" class="btn btn-success btn-format" value="Login">
            </div>
            <p></p>
            Do not have an Account?
            @Html.ActionLink("Signup here", "Register", "HomeHealthCare", new { area = "" }, null)
        </form>
    </div>
    <div id="validation-success"></div>

</body>
</html>

HomeHealthCareMVC/Views/HomeHealthCare/Register.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/Register.css" rel="stylesheet" />
    @*<script src="~/Scripts/jquery-3.4.1.min.js"></script>*@
    <script defer src="~/Scripts/Register.js"></script>
</head>
<body>
    <div class="container">
        <form id="signup" class="form">
            <h1>HomeHealthCare</h1>
            <div class="form-field">
                <label for="firstname">FirstName</label>
                <input type="text" name="firstname" id="txtFirstName" autocomplete="off">
                <small></small>
            </div>
            <div class="form-field">
                <label for="lastname">LastName</label>
                <input type="text" name="lastname" id="txtLastName" autocomplete="off">
                <small></small>
            </div>

            <div class="form-field">
                <label for="email">Email:</label>
                <input type="text" name="email" id="txtEmail" autocomplete="off">
                <small></small>
            </div>

            <div class="form-field">
                <label for="password">Password:</label>
                <input type="password" name="password" id="txtPassword" autocomplete="off">
                <small></small>
            </div>


            <div class="form-field">
                <label for="confirmpassword">Confirm Password:</label>
                <input type="password" name="confirmpassword" id="txtConfirmPassword" autocomplete="off">
                <small></small>
            </div>



            <div class="form-field">
                <label for="dob">DOB</label>
                <input type="date" name="dob" id="txtDOB" autocomplete="off">
                <small></small>
            </div>
            <div class="form-field">
                <label for="user Type">Type of User:</label>
                <select name="Type Of User" id="txttype">
                    <option value="doctor">Doctor</option>
                    <option value="patient">Patient</option>
                </select>
                <small></small>
            </div>

            <div class="form-field">
                <input type="submit" class="btn btn-success btn-format" value="Register">
            </div>

        </form>

    </div>




</body>
</html>

HomeHealthCareMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body  style="background-color:floralwhite">
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>